import 'copsoq_model.dart';

class CopsoqData {
  static const List<CopsoqDimension> dimensions = [
    // DOMÍNIO 1: EXIGÊNCIAS LABORAIS
    CopsoqDimension(
      id: 'exig_quantitativas',
      name: 'Exigências Quantitativas',
      domainId: 'exigencias_laborais',
      domainName: 'Exigências Laborais',
      questionIds: ['q1', 'q2', 'q3'],
    ),
    CopsoqDimension(
      id: 'ritmo_trabalho',
      name: 'Ritmo de Trabalho',
      domainId: 'exigencias_laborais',
      domainName: 'Exigências Laborais',
      questionIds: ['q4'],
    ),
    CopsoqDimension(
      id: 'exig_cognitivas',
      name: 'Exigências Cognitivas',
      domainId: 'exigencias_laborais',
      domainName: 'Exigências Laborais',
      questionIds: ['q5', 'q6', 'q7'],
    ),
    CopsoqDimension(
      id: 'exig_emocionais',
      name: 'Exigências Emocionais',
      domainId: 'exigencias_laborais',
      domainName: 'Exigências Laborais',
      questionIds: ['q8'],
    ),
    // DOMÍNIO 2: ORGANIZAÇÃO E CONTEÚDO DO TRABALHO
    CopsoqDimension(
      id: 'influencia_trabalho',
      name: 'Influência no Trabalho',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      questionIds: ['q9', 'q10', 'q11', 'q12'],
    ),
    CopsoqDimension(
      id: 'poss_desenvolvimento',
      name: 'Possibilidades de Desenvolvimento',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      questionIds: ['q13', 'q14', 'q15'],
    ),
    CopsoqDimension(
      id: 'significado_trabalho',
      name: 'Significado do Trabalho',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      questionIds: ['q16', 'q17', 'q18'],
    ),
    CopsoqDimension(
      id: 'compromisso_trabalho',
      name: 'Compromisso face ao Local de Trabalho',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      questionIds: ['q19', 'q20'],
    ),
    // DOMÍNIO 3: RELAÇÕES SOCIAIS E LIDERANÇA
    CopsoqDimension(
      id: 'previsibilidade',
      name: 'Previsibilidade',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      questionIds: ['q21', 'q22'],
    ),
    CopsoqDimension(
      id: 'transparencia',
      name: 'Transparência do Papel Laboral Desempenhado',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      questionIds: ['q23', 'q24', 'q25'],
    ),
    CopsoqDimension(
      id: 'recompensas',
      name: 'Recompensas',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      questionIds: ['q26', 'q27', 'q28'],
    ),
    CopsoqDimension(
      id: 'conflitos_laborais',
      name: 'Conflitos Laborais',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      questionIds: ['q29', 'q30', 'q31'],
    ),
    CopsoqDimension(
      id: 'apoio_colegas',
      name: 'Apoio Social de Colegas',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      questionIds: ['q32', 'q33', 'q34'],
    ),
    CopsoqDimension(
      id: 'apoio_superiores',
      name: 'Apoio Social de Superiores',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      questionIds: ['q35', 'q36', 'q37'],
    ),
    CopsoqDimension(
      id: 'comunidade_social',
      name: 'Comunidade Social no Trabalho',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      questionIds: ['q38', 'q39', 'q40'],
    ),
    CopsoqDimension(
      id: 'qualidade_lideranca',
      name: 'Qualidade da Liderança',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      questionIds: ['q41', 'q42', 'q43', 'q44'],
    ),
    // DOMÍNIO 4: VALORES NO LOCAL DE TRABALHO
    CopsoqDimension(
      id: 'confianca_horizontal',
      name: 'Confiança Horizontal',
      domainId: 'valores_trabalho',
      domainName: 'Valores no Local de Trabalho',
      questionIds: ['q45', 'q46', 'q47'],
    ),
    CopsoqDimension(
      id: 'confianca_vertical',
      name: 'Confiança Vertical',
      domainId: 'valores_trabalho',
      domainName: 'Valores no Local de Trabalho',
      questionIds: ['q48', 'q49', 'q50'],
    ),
    CopsoqDimension(
      id: 'justica_respeito',
      name: 'Justiça e Respeito',
      domainId: 'valores_trabalho',
      domainName: 'Valores no Local de Trabalho',
      questionIds: ['q51', 'q52', 'q53'],
    ),
    // DOMÍNIO 5: SAÚDE E BEM-ESTAR
    CopsoqDimension(
      id: 'autoeficacia',
      name: 'Auto-Eficácia',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      questionIds: ['q54', 'q55'],
    ),
    CopsoqDimension(
      id: 'conflito_trabalho_familia',
      name: 'Conflito Trabalho/Família',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      questionIds: ['q56', 'q57', 'q58'],
    ),
    CopsoqDimension(
      id: 'saude_geral',
      name: 'Saúde Geral',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      questionIds: ['q59'],
    ),
    CopsoqDimension(
      id: 'burnout',
      name: 'Burnout',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      questionIds: ['q60', 'q61'],
    ),
    CopsoqDimension(
      id: 'stress',
      name: 'Stress',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      questionIds: ['q62', 'q63'],
    ),
    CopsoqDimension(
      id: 'sintomas_depressivos',
      name: 'Sintomas Depressivos',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      questionIds: ['q64', 'q65'],
    ),
    CopsoqDimension(
      id: 'problemas_dormir',
      name: 'Problemas em Dormir',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      questionIds: ['q66', 'q67'],
    ),
    CopsoqDimension(
      id: 'comportamentos_ofensivos',
      name: 'Comportamentos Ofensivos',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      questionIds: ['q68', 'q69', 'q70'],
    ),
  ];

  static const List<CopsoqQuestion> questions = [
    // EXIGÊNCIAS QUANTITATIVAS
    CopsoqQuestion(
      id: 'q1',
      number: 1,
      text: 'Com que frequência não tem tempo para completar todas as suas tarefas no trabalho?',
      dimensionId: 'exig_quantitativas',
      dimensionName: 'Exigências Quantitativas',
      domainId: 'exigencias_laborais',
      domainName: 'Exigências Laborais',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q2',
      number: 2,
      text: 'Com que frequência precisa trabalhar horas extra?',
      dimensionId: 'exig_quantitativas',
      dimensionName: 'Exigências Quantitativas',
      domainId: 'exigencias_laborais',
      domainName: 'Exigências Laborais',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q3',
      number: 3,
      text: 'Com que frequência tem que trabalhar muito rapidamente?',
      dimensionId: 'exig_quantitativas',
      dimensionName: 'Exigências Quantitativas',
      domainId: 'exigencias_laborais',
      domainName: 'Exigências Laborais',
      scaleType: 'frequency',
    ),
    // RITMO DE TRABALHO
    CopsoqQuestion(
      id: 'q4',
      number: 4,
      text: 'O seu trabalho exige que você trabalhe em um ritmo acelerado?',
      dimensionId: 'ritmo_trabalho',
      dimensionName: 'Ritmo de Trabalho',
      domainId: 'exigencias_laborais',
      domainName: 'Exigências Laborais',
      scaleType: 'frequency',
    ),
    // EXIGÊNCIAS COGNITIVAS
    CopsoqQuestion(
      id: 'q5',
      number: 5,
      text: 'O seu trabalho exige que tome decisões difíceis?',
      dimensionId: 'exig_cognitivas',
      dimensionName: 'Exigências Cognitivas',
      domainId: 'exigencias_laborais',
      domainName: 'Exigências Laborais',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q6',
      number: 6,
      text: 'O seu trabalho exige que memorize muitas coisas?',
      dimensionId: 'exig_cognitivas',
      dimensionName: 'Exigências Cognitivas',
      domainId: 'exigencias_laborais',
      domainName: 'Exigências Laborais',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q7',
      number: 7,
      text: 'O seu trabalho exige que você seja criativo(a)?',
      dimensionId: 'exig_cognitivas',
      dimensionName: 'Exigências Cognitivas',
      domainId: 'exigencias_laborais',
      domainName: 'Exigências Laborais',
      scaleType: 'frequency',
    ),
    // EXIGÊNCIAS EMOCIONAIS
    CopsoqQuestion(
      id: 'q8',
      number: 8,
      text: 'O seu trabalho é emocionalmente exigente?',
      dimensionId: 'exig_emocionais',
      dimensionName: 'Exigências Emocionais',
      domainId: 'exigencias_laborais',
      domainName: 'Exigências Laborais',
      scaleType: 'frequency',
    ),
    // INFLUÊNCIA NO TRABALHO
    CopsoqQuestion(
      id: 'q9',
      number: 9,
      text: 'Tem grande influência no seu trabalho?',
      dimensionId: 'influencia_trabalho',
      dimensionName: 'Influência no Trabalho',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q10',
      number: 10,
      text: 'Participa na decisão sobre com quem trabalha?',
      dimensionId: 'influencia_trabalho',
      dimensionName: 'Influência no Trabalho',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q11',
      number: 11,
      text: 'Você pode influenciar a quantidade de trabalho que lhe é atribuído?',
      dimensionId: 'influencia_trabalho',
      dimensionName: 'Influência no Trabalho',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q12',
      number: 12,
      text: 'Tem algum controlo sobre a forma como realiza o seu trabalho?',
      dimensionId: 'influencia_trabalho',
      dimensionName: 'Influência no Trabalho',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      scaleType: 'frequency',
    ),
    // POSSIBILIDADES DE DESENVOLVIMENTO
    CopsoqQuestion(
      id: 'q13',
      number: 13,
      text: 'O seu trabalho exige que tome a iniciativa?',
      dimensionId: 'poss_desenvolvimento',
      dimensionName: 'Possibilidades de Desenvolvimento',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q14',
      number: 14,
      text: 'O seu trabalho oferece oportunidade de aprender coisas novas?',
      dimensionId: 'poss_desenvolvimento',
      dimensionName: 'Possibilidades de Desenvolvimento',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q15',
      number: 15,
      text: 'O seu trabalho permite que você utilize suas competências ou especializações?',
      dimensionId: 'poss_desenvolvimento',
      dimensionName: 'Possibilidades de Desenvolvimento',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      scaleType: 'frequency',
    ),
    // SIGNIFICADO DO TRABALHO
    CopsoqQuestion(
      id: 'q16',
      number: 16,
      text: 'O seu trabalho tem algum significado para você?',
      dimensionId: 'significado_trabalho',
      dimensionName: 'Significado do Trabalho',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q17',
      number: 17,
      text: 'Sente que o seu trabalho é importante?',
      dimensionId: 'significado_trabalho',
      dimensionName: 'Significado do Trabalho',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q18',
      number: 18,
      text: 'Você se sente motivado(a) e envolvido(a) com seu trabalho?',
      dimensionId: 'significado_trabalho',
      dimensionName: 'Significado do Trabalho',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      scaleType: 'frequency',
    ),
    // COMPROMISSO
    CopsoqQuestion(
      id: 'q19',
      number: 19,
      text: 'Gosta de falar com outras pessoas sobre o seu local de trabalho?',
      dimensionId: 'compromisso_trabalho',
      dimensionName: 'Compromisso face ao Local de Trabalho',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q20',
      number: 20,
      text: 'Sente que os problemas do seu local de trabalho são seus também?',
      dimensionId: 'compromisso_trabalho',
      dimensionName: 'Compromisso face ao Local de Trabalho',
      domainId: 'organizacao_conteudo',
      domainName: 'Organização e Conteúdo do Trabalho',
      scaleType: 'frequency',
    ),
    // PREVISIBILIDADE
    CopsoqQuestion(
      id: 'q21',
      number: 21,
      text: 'Você é informado(a) com antecedência sobre decisões importantes, mudanças ou planos para o futuro?',
      dimensionId: 'previsibilidade',
      dimensionName: 'Previsibilidade',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q22',
      number: 22,
      text: 'Recebe toda a informação de que necessita para fazer bem o seu trabalho?',
      dimensionId: 'previsibilidade',
      dimensionName: 'Previsibilidade',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    // TRANSPARÊNCIA
    CopsoqQuestion(
      id: 'q23',
      number: 23,
      text: 'O seu trabalho apresenta objetivos claros?',
      dimensionId: 'transparencia',
      dimensionName: 'Transparência do Papel Laboral Desempenhado',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q24',
      number: 24,
      text: 'Sabe exatamente quais são as suas responsabilidades?',
      dimensionId: 'transparencia',
      dimensionName: 'Transparência do Papel Laboral Desempenhado',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q25',
      number: 25,
      text: 'Sabe exatamente o que é esperado de você?',
      dimensionId: 'transparencia',
      dimensionName: 'Transparência do Papel Laboral Desempenhado',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    // RECOMPENSAS
    CopsoqQuestion(
      id: 'q26',
      number: 26,
      text: 'O seu trabalho é reconhecido e valorizado pela gestão/direção?',
      dimensionId: 'recompensas',
      dimensionName: 'Recompensas',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q27',
      number: 27,
      text: 'A gestão/direção da empresa respeita você?',
      dimensionId: 'recompensas',
      dimensionName: 'Recompensas',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q28',
      number: 28,
      text: 'Você é tratado(a) de forma justa no seu local de trabalho?',
      dimensionId: 'recompensas',
      dimensionName: 'Recompensas',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    // CONFLITOS LABORAIS
    CopsoqQuestion(
      id: 'q29',
      number: 29,
      text: 'É necessário fazer coisas que considera deverem ser feitas de outra forma?',
      dimensionId: 'conflitos_laborais',
      dimensionName: 'Conflitos Laborais',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q30',
      number: 30,
      text: 'O seu trabalho apresenta exigências contraditórias ou conflituosas?',
      dimensionId: 'conflitos_laborais',
      dimensionName: 'Conflitos Laborais',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q31',
      number: 31,
      text: 'Por vezes tem que ignorar determinadas regras ou procedimentos para conseguir realizar o seu trabalho?',
      dimensionId: 'conflitos_laborais',
      dimensionName: 'Conflitos Laborais',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    // APOIO SOCIAL DE COLEGAS
    CopsoqQuestion(
      id: 'q32',
      number: 32,
      text: 'Com que frequência recebe ajuda e apoio dos seus colegas de trabalho?',
      dimensionId: 'apoio_colegas',
      dimensionName: 'Apoio Social de Colegas',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q33',
      number: 33,
      text: 'Com que frequência seus colegas estão dispostos a ouvi-lo(a) quando você fala de seus problemas no trabalho?',
      dimensionId: 'apoio_colegas',
      dimensionName: 'Apoio Social de Colegas',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q34',
      number: 34,
      text: 'Com que frequência os seus colegas falam consigo sobre a forma como realiza o seu trabalho?',
      dimensionId: 'apoio_colegas',
      dimensionName: 'Apoio Social de Colegas',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    // APOIO SOCIAL DE SUPERIORES
    CopsoqQuestion(
      id: 'q35',
      number: 35,
      text: 'Com que frequência recebe ajuda e apoio do seu superior imediato?',
      dimensionId: 'apoio_superiores',
      dimensionName: 'Apoio Social de Superiores',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q36',
      number: 36,
      text: 'Com que frequência o seu superior imediato fala consigo sobre a forma como realiza o seu trabalho?',
      dimensionId: 'apoio_superiores',
      dimensionName: 'Apoio Social de Superiores',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q37',
      number: 37,
      text: 'Com que frequência o seu superior imediato está disposto a ouvi-lo(a) quando você fala de seus problemas no trabalho?',
      dimensionId: 'apoio_superiores',
      dimensionName: 'Apoio Social de Superiores',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    // COMUNIDADE SOCIAL NO TRABALHO
    CopsoqQuestion(
      id: 'q38',
      number: 38,
      text: 'Existe um bom ambiente de trabalho entre você e seus colegas?',
      dimensionId: 'comunidade_social',
      dimensionName: 'Comunidade Social no Trabalho',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q39',
      number: 39,
      text: 'Existe boa cooperação entre os colegas de trabalho?',
      dimensionId: 'comunidade_social',
      dimensionName: 'Comunidade Social no Trabalho',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q40',
      number: 40,
      text: 'Os seus colegas de trabalho respeitam você?',
      dimensionId: 'comunidade_social',
      dimensionName: 'Comunidade Social no Trabalho',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    // QUALIDADE DA LIDERANÇA
    CopsoqQuestion(
      id: 'q41',
      number: 41,
      text: 'O seu superior imediato garante que cada trabalhador(a) tem boas oportunidades de desenvolvimento?',
      dimensionId: 'qualidade_lideranca',
      dimensionName: 'Qualidade da Liderança',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q42',
      number: 42,
      text: 'O seu superior imediato dá prioridade à satisfação no trabalho?',
      dimensionId: 'qualidade_lideranca',
      dimensionName: 'Qualidade da Liderança',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q43',
      number: 43,
      text: 'O seu superior imediato é bom a planear o trabalho?',
      dimensionId: 'qualidade_lideranca',
      dimensionName: 'Qualidade da Liderança',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q44',
      number: 44,
      text: 'O seu superior imediato resolve bem os conflitos?',
      dimensionId: 'qualidade_lideranca',
      dimensionName: 'Qualidade da Liderança',
      domainId: 'relacoes_sociais',
      domainName: 'Relações Sociais e Liderança',
      scaleType: 'frequency',
    ),
    // CONFIANÇA HORIZONTAL
    CopsoqQuestion(
      id: 'q45',
      number: 45,
      text: 'Você pode confiar nas informações provenientes da gestão/direção?',
      dimensionId: 'confianca_horizontal',
      dimensionName: 'Confiança Horizontal',
      domainId: 'valores_trabalho',
      domainName: 'Valores no Local de Trabalho',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q46',
      number: 46,
      text: 'Os conflitos são resolvidos de uma forma justa?',
      dimensionId: 'confianca_horizontal',
      dimensionName: 'Confiança Horizontal',
      domainId: 'valores_trabalho',
      domainName: 'Valores no Local de Trabalho',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q47',
      number: 47,
      text: 'O trabalho é distribuído de forma justa?',
      dimensionId: 'confianca_horizontal',
      dimensionName: 'Confiança Horizontal',
      domainId: 'valores_trabalho',
      domainName: 'Valores no Local de Trabalho',
      scaleType: 'frequency',
    ),
    // CONFIANÇA VERTICAL
    CopsoqQuestion(
      id: 'q48',
      number: 48,
      text: 'Os seus colegas de trabalho são de confiança?',
      dimensionId: 'confianca_vertical',
      dimensionName: 'Confiança Vertical',
      domainId: 'valores_trabalho',
      domainName: 'Valores no Local de Trabalho',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q49',
      number: 49,
      text: 'Existe boa cooperação entre você e seus colegas de trabalho?',
      dimensionId: 'confianca_vertical',
      dimensionName: 'Confiança Vertical',
      domainId: 'valores_trabalho',
      domainName: 'Valores no Local de Trabalho',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q50',
      number: 50,
      text: 'Os seus colegas de trabalho são de respeito?',
      dimensionId: 'confianca_vertical',
      dimensionName: 'Confiança Vertical',
      domainId: 'valores_trabalho',
      domainName: 'Valores no Local de Trabalho',
      scaleType: 'frequency',
    ),
    // JUSTIÇA E RESPEITO
    CopsoqQuestion(
      id: 'q51',
      number: 51,
      text: 'Você é tratado(a) com respeito pelos seus superiores?',
      dimensionId: 'justica_respeito',
      dimensionName: 'Justiça e Respeito',
      domainId: 'valores_trabalho',
      domainName: 'Valores no Local de Trabalho',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q52',
      number: 52,
      text: 'Você é respeitado(a) pelos seus colegas?',
      dimensionId: 'justica_respeito',
      dimensionName: 'Justiça e Respeito',
      domainId: 'valores_trabalho',
      domainName: 'Valores no Local de Trabalho',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q53',
      number: 53,
      text: 'No seu local de trabalho, você é tratado(a) de forma justa?',
      dimensionId: 'justica_respeito',
      dimensionName: 'Justiça e Respeito',
      domainId: 'valores_trabalho',
      domainName: 'Valores no Local de Trabalho',
      scaleType: 'frequency',
    ),
    // AUTO-EFICÁCIA
    CopsoqQuestion(
      id: 'q54',
      number: 54,
      text: 'Consegue resolver os problemas que surgem no seu trabalho, se fizer o esforço necessário?',
      dimensionId: 'autoeficacia',
      dimensionName: 'Auto-Eficácia',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'intensity',
    ),
    CopsoqQuestion(
      id: 'q55',
      number: 55,
      text: 'Consegue encontrar formas de contornar os obstáculos, quando tenta fazer algo de novo no trabalho?',
      dimensionId: 'autoeficacia',
      dimensionName: 'Auto-Eficácia',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'intensity',
    ),
    // CONFLITO TRABALHO/FAMÍLIA
    CopsoqQuestion(
      id: 'q56',
      number: 56,
      text: 'Com que frequência sente que o trabalho consome energia demais que deveria ser dedicada à família/vida pessoal?',
      dimensionId: 'conflito_trabalho_familia',
      dimensionName: 'Conflito Trabalho/Família',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q57',
      number: 57,
      text: 'Com que frequência sente que o trabalho toma tempo demais que deveria ser dedicado à família/vida pessoal?',
      dimensionId: 'conflito_trabalho_familia',
      dimensionName: 'Conflito Trabalho/Família',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q58',
      number: 58,
      text: 'Seus colegas tratam você bem quando tem problemas na família/vida pessoal?',
      dimensionId: 'conflito_trabalho_familia',
      dimensionName: 'Conflito Trabalho/Família',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'frequency',
    ),
    // SAÚDE GERAL
    CopsoqQuestion(
      id: 'q59',
      number: 59,
      text: 'Em geral, sente que a sua saúde é:',
      dimensionId: 'saude_geral',
      dimensionName: 'Saúde Geral',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'intensity',
    ),
    // BURNOUT
    CopsoqQuestion(
      id: 'q60',
      number: 60,
      text: 'Com que frequência você se sente esgotado(a) fisicamente?',
      dimensionId: 'burnout',
      dimensionName: 'Burnout',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q61',
      number: 61,
      text: 'Com que frequência você se sente emocionalmente esgotado(a)?',
      dimensionId: 'burnout',
      dimensionName: 'Burnout',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'frequency',
    ),
    // STRESS
    CopsoqQuestion(
      id: 'q62',
      number: 62,
      text: 'Com que frequência sente tensão?',
      dimensionId: 'stress',
      dimensionName: 'Stress',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q63',
      number: 63,
      text: 'Com que frequência você sente que tudo parece difícil de controlar?',
      dimensionId: 'stress',
      dimensionName: 'Stress',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'frequency',
    ),
    // SINTOMAS DEPRESSIVOS
    CopsoqQuestion(
      id: 'q64',
      number: 64,
      text: 'Com que frequência se sente triste?',
      dimensionId: 'sintomas_depressivos',
      dimensionName: 'Sintomas Depressivos',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q65',
      number: 65,
      text: 'Com que frequência se sente sem esperança em relação ao futuro?',
      dimensionId: 'sintomas_depressivos',
      dimensionName: 'Sintomas Depressivos',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'frequency',
    ),
    // PROBLEMAS EM DORMIR
    CopsoqQuestion(
      id: 'q66',
      number: 66,
      text: 'Com que frequência tem dificuldade em adormecer?',
      dimensionId: 'problemas_dormir',
      dimensionName: 'Problemas em Dormir',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q67',
      number: 67,
      text: 'Com que frequência acorda a meio da noite e tem dificuldade em adormecer de novo?',
      dimensionId: 'problemas_dormir',
      dimensionName: 'Problemas em Dormir',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'frequency',
    ),
    // COMPORTAMENTOS OFENSIVOS
    CopsoqQuestion(
      id: 'q68',
      number: 68,
      text: 'No seu local de trabalho, você é exposto(a) a comportamentos de intimidação (assédio moral)?',
      dimensionId: 'comportamentos_ofensivos',
      dimensionName: 'Comportamentos Ofensivos',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q69',
      number: 69,
      text: 'No seu local de trabalho, você é exposto(a) a assédio sexual?',
      dimensionId: 'comportamentos_ofensivos',
      dimensionName: 'Comportamentos Ofensivos',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'frequency',
    ),
    CopsoqQuestion(
      id: 'q70',
      number: 70,
      text: 'No seu local de trabalho, você é exposto(a) a ameaças de violência?',
      dimensionId: 'comportamentos_ofensivos',
      dimensionName: 'Comportamentos Ofensivos',
      domainId: 'saude_bemestar',
      domainName: 'Saúde e Bem-estar',
      scaleType: 'frequency',
    ),
  ];

  static const List<String> frequencyScale = [
    'Nunca/Quase nunca',
    'Raramente',
    'Às vezes',
    'Frequentemente',
    'Sempre',
  ];

  static const List<String> intensityScale = [
    'Nada/Quase nada',
    'Um pouco',
    'Moderadamente',
    'Muito',
    'Extremamente',
  ];

  // Dimensões que são favoráveis quando score é ALTO (positivas)
  // Nas demais, score alto = RISCO
  static const Set<String> positiveDimensions = {
    'influencia_trabalho',
    'poss_desenvolvimento',
    'significado_trabalho',
    'compromisso_trabalho',
    'previsibilidade',
    'transparencia',
    'recompensas',
    'apoio_colegas',
    'apoio_superiores',
    'comunidade_social',
    'qualidade_lideranca',
    'confianca_horizontal',
    'confianca_vertical',
    'justica_respeito',
    'autoeficacia',
    'saude_geral',
  };

  static String getColorForScore(String dimensionId, double score) {
    final isPositive = positiveDimensions.contains(dimensionId);
    if (isPositive) {
      if (score >= 3.67) return 'green';
      if (score >= 2.34) return 'yellow';
      return 'red';
    } else {
      if (score <= 2.33) return 'green';
      if (score <= 3.66) return 'yellow';
      return 'red';
    }
  }

  static CopsoqDimension? getDimensionById(String id) {
    try {
      return dimensions.firstWhere((d) => d.id == id);
    } catch (_) {
      return null;
    }
  }

  static List<CopsoqQuestion> getQuestionsForDimension(String dimensionId) {
    return questions.where((q) => q.dimensionId == dimensionId).toList();
  }
}
